### ISSUE TITLE
change the description of the address text field

### ISSUE THREAD

**Issue by danorys** [mangrove-labs/cutgroup-website#12]
Since pressing enter moves the user to the next field, users are unable to insert carrier return - line feeds (CRLF) between street, apartment, and city, state and zip code lines.

**Comment by ErnieAtLYD** [comment]
What I'll do instead is change the description of the address text from:

```
We will need your address to mail your gift card. Example: 123 Main Street
```

to

```
We will need your address to mail your gift card. Example: 123 Main Street Apt #2, Miami FL
```

**Comment by ErnieAtLYD** [comment]
Added to the typeform.
