### ISSUE TITLE
Should addresses outside of Miami-Dade be accepted? 

### ISSUE THREAD

**Issue by danorys** [mangrove-labs/cutgroup-website#13]
Since CUT Group Miami is only open to users in Miami, should the web site automatically exclude zip codes outside of Miami-Dade? For instance, I was able enter 33432 which is Boca Raton.

**Comment by ErnieAtLYD** [comment]
Technically folks outside of Boca Raton can't be a part of the CUTGroup. I've changed the field so that it's a drop down (but you can type inside of it) of all the zip codes available in the county.
