### ISSUE TITLE
Should users receive confirmation of signing  up for Cut Group Miami? 

### ISSUE THREAD

**Issue by danorys** [mangrove-labs/cutgroup-website#14]
I apparently signed up successfully for the Cut Group Miami, but did not receive the typical e-mail notification to confirm sign up. 

If we are going to provide them with a Visa card, I recommend requiring applicants to click on a link to validate the e-mail address is valid as well. If nothing else, this will prevent a robot from sending in a bunch of fictitious submissions.

**Comment by ErnieAtLYD** [comment]
Yeah, that's a bug on my part to address trough Typeform.

**Comment by ErnieAtLYD** [comment]
Here's the copy I'm going to use for both the e-mail notification and the thank you screen:

```
Thanks for applying to the Miami CUTGroup, [NAME].

We will verify your sign-up soon. Once verified, we will send you a $5 VISA gift card.

If you live anywhere in Miami-Dade County, you are eligible to be a CUTGroup tester. 
After you have signed up, you’ll be part of the CUTGroup and will receive email 
notifications when we have new tests coming up.
```

What do you think?

**Comment by ErnieAtLYD** [comment]
I'm just gonna go with this. Feel free to test the staging and live quizzes.
