### ISSUE TITLE
Bug in responsive CSS, "Get Started" in mobile view

### ISSUE THREAD

**Issue by ErnieAtLYD** [mangrove-labs/cutgroup-website#25]
![image](https://cloud.githubusercontent.com/assets/33945/17843766/ea97fb8c-67ff-11e6-8d0f-68126ca69b50.png)

**Comment by ErnieAtLYD** [comment]
Hey @jonmalave - So @phiden brings up a good point to your pull request at #28; there's a SASS file in there. If any developer were to go in and run the sass, you would lose your changes within CSS. Can you add your changes within the SASS as well?

**Comment by jonmalave** [comment]
@ErnieAtLYD @phiden sure thing, will do!

**Comment by jonmalave** [comment]
@ErnieAtLYD Fixed, added the update in my latest pull request. I forgot to seperate the updates into branches. Had a repo issue on my end so had to re-clone master, and copy updates over. I'll continue separating issues into new branches and pulls of course going foward.

**Comment by ErnieAtLYD** [comment]
Looks good!
https://github.com/mangrove-labs/cutgroup-website/pull/32
