### ISSUE TITLE
Change venue from LAB Miami to CIC Miami

### ISSUE THREAD

**Issue by ErnieAtLYD** [mangrove-labs/cutgroup-website#35]
Starting Labor Day we are moving Code for Miami weekly hack nights to CIC Miami. The web pages should be changed to reflect this.

**Comment by jonmalave** [comment]
@ErnieAtLYD I don't see anywhere on the site where Lab Miami is listed. Please advise.

**Comment by ErnieAtLYD** [comment]
You're... you're totally right. Maybe I was thinking the Code for Miami website. Sorry about that!
