### ISSUE TITLE
Get Haitian translations of website

### ISSUE THREAD

**Issue by ErnieAtLYD** [mangrove-labs/cutgroup-website#9]
- [x] Spin off a ht.html
- [x] Embed the Haitian typeform quiz (get the embedded HTML from Ernie)
- [x] Link the Creole link to the English and Spanish pages. Use the word `Kreyol`
- [x] Use the copy at this page for now: https://docs.google.com/spreadsheets/d/165zMdSjUH6xMDYZwZ5GCqwetOkm9YEO6v8NKpcFQUAg/edit#gid=1021946456 - this will need to be finalized with a translation service anyway so if there is stuff missing, note this and then let me know.

**Comment by jonmalave** [comment]
@ErnieAtLYD When you have a moment please send the embed code for the Haitian typeform quiz, either here or via #Slack is fine. 

**[Question]** Do you want to add Kreyol as an additional link to the top nav bar, or would you like to create a drop down menu labeled as Language, hover over or click to display options?

**Comment by ErnieAtLYD** [comment]
> Do you want to add Kreyol as an additional link to the top nav bar, or would you like to create a drop down menu labeled as Language, hover over or click to display options? 

For now, let's just do an additional link. If it's necessary we'll make it an additional thing.

As far the Haitian typeform:

```
<!-- Change the width and height values to suit you best -->
<div class="typeform-widget" data-url="https://ernieatlyd.typeform.com/to/AJFRpB" data-text="CUTGroup form (HT)" style="width:100%;height:500px;"></div>
<script>(function(){var qs,js,q,s,d=document,gi=d.getElementById,ce=d.createElement,gt=d.getElementsByTagName,id='typef_orm',b='https://s3-eu-west-1.amazonaws.com/share.typeform.com/';if(!gi.call(d,id)){js=ce.call(d,'script');js.id=id;js.src=b+'widget.js';q=gt.call(d,'script')[0];q.parentNode.insertBefore(js,q)}})()</script>
```

You'll want to match the style width and height to what @CristinaSolana used for the English and Spanish forms however.

**Comment by jonmalave** [comment]
@ErnieAtLYD Completed! Added `<a href="#tester" class="button scrolly">Why should I test?</a>` translation to row 14, was missing.

**Comment by ErnieAtLYD** [comment]
Looks good! 
https://github.com/mangrove-labs/cutgroup-website/pull/32
